from tkinter import *
from tkcalendar import Calendar, DateEntry
root=Tk()
root.geometry("900x800")


def get_data():
	print("First Name is :%s"%fname.get())
	print("middle Name is :%s"%mname.get())
	print("last Name is :%s"%lname.get())
	print("Order-Item Name is :%s"%oitem.get())
	print("Total Amount is :%d"%total.get())
	print("Contact NUmber is :%d"%cont.get())
	print("Email Address is :%s"%email.get())
	print("Receiving Address is :%s"%addr.get())
	
Label(text="ONLINE ORDER FORM",font="comissansms 25 bold").grid(row=0,column=1)
Label(text="First Name:",font="comissansms 15 bold italic").grid(row=3,column=0)
fname=StringVar()
mname=StringVar()
lname=StringVar()
Entry(root,textvariable=fname,font="calibre 9 normal").grid(row=3,column=1)
Label(text="Middle Name:",font="comissansms 15 bold").grid(row=4,column=0)
Entry(root,textvariable=mname,font="calibre 9 normal").grid(row=4,column=1)
Label(text="Last Name:",font="comissansms 15 bold").grid(row=5,column=0)
Entry(root,textvariable=lname,font="calibre 9 normal").grid(row=5,column=1)
Label(text="Gender",font="comissansms 15 bold").grid(row=6,column=0)
var=IntVar()
Radiobutton(text="Male",variable=var,value=0).grid(row=6,column=1)
Radiobutton(text="Female",variable=var,value=1).grid(row=6,column=2)
Radiobutton(text="Others",variable=var,value=2).grid(row=6,column=3)
oitem=StringVar()
total=IntVar()
cont=IntVar()
email=StringVar()
addr=StringVar()

Label(text="Order Item:",font="comissansms 15 bold").grid(row=7,column=0)
Entry(root,textvariable=oitem,font="calibre 9 normal").grid(row=7,column=1)
Label(text="Total Amount:",font="comissansms 15 bold").grid(row=8,column=0)
Entry(root,textvariable=total,font="calibre 9 normal").grid(row=8,column=1)

Label(text="Contact:",font="comissansms 15 bold").grid(row=9,column=0)
Entry(root,textvariable=cont,font="calibre 9 normal").grid(row=9,column=1)
Label(text="Email Address:", font="comissansms 15 bold").grid(row=10,column=0)
Entry(root,textvariable=email,font="calibre 9 normal").grid(row=10,column=1)
Label(text="Receving Address:",font="comissansms 15 bold").grid(row=11,column=0)
Entry(root,textvariable=addr,font="calibre 9 normal").grid(row=11,column=1)
Label(text="Delivered Date:",font="comissansms 15 bold").grid(row=12,column=0)
DateEntry(root, width=16, background= "magenta3", foreground="white",bd=2).grid(row=12,column=1)
Label(text="Received Date:",font="comissansms 15 bold").grid(row=13,column=0)
DateEntry(root, width=16, background= "magenta3", foreground="white",bd=2).grid(row=13,column=1)

Button(text="submit", command=get_data, width=15).grid(row=15,column=2)
root.mainloop()
